name: Tests

on:
  push:

jobs:
  test-mobile:
    name: Test Mobile App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm run -r test
  testgo:
    name: Test Go
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
          cache-dependency-path: "go.sum"

      - name: Lint
        run: go vet ./...

      - name: Test
        run: go test ./... -race

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.57
          args: --timeout=10m ./...
